replace dockerhub images for tasks and actions
- runway ci currently fails pulling the task images to run the tasks.

- use floating golang version for unit tests

  we've updated a lot of things to go 1.21. 1.21 introduced a new directive
  `toolchain`. This directive doesn't work in older versions of go and throws an
  error. This updates the image in use to use latest golang 1.x instead of
  pinning it to 1.19.

  fixes:
  ```
  Attaching to backup-and-restore-sdk-release_unit-blobstore-azure_1
  unit-blobstore-azure_1           | + pushd /backup-and-restore-sdk-release/src/azure-blobstore-backup-restore
  unit-blobstore-azure_1           | + go run github.com/onsi/ginkgo/v2/ginkgo -mod vendor -r --keep-going -p --skip-package contract_test
  unit-blobstore-azure_1           | /backup-and-restore-sdk-release/src/azure-blobstore-backup-restore /go
  unit-blobstore-azure_1           | go: errors parsing go.mod:
  unit-blobstore-azure_1           | /backup-and-restore-sdk-release/src/azure-blobstore-backup-restore/go.mod:5: unknown directive: toolchain
  backup-and-restore-sdk-release_unit-blobstore-azure_1 exited with code 1
  1
  Aborting on container exit...
  make: *** [Makefile:78: docker-unit-blobstore-azure] Error 1
  Error: Process completed with exit code 2.
  ```

- change image source

  turns out that the image maintained by bosh team @ vmware is at

  `bosh/cli` and not `cloudfoundry/bosh-cli`

  while it had the same problem as `cloudfoundry/bosh-cli` it has been fixed
  for the latest image. what builds `cloudfoundry/bosh-cli` is currently a mystery
  to me so the image is switched to a known source.

add apt update before install